### ISSUE TITLE
Database Setup

### ISSUE THREAD

**Issue by tylerpporter** [tylerpporter/find_my_market_api#10]
- [x] Create Postgres DB
    - [x] Test
    - [x] Development
- [x] Create tables 
    - [x] users
    - [x] markets
- [x] Create new fastapi app 
    - [x] Connect to DB
