### ISSUE TITLE
Setup Pydantic Models for OAuth responses

### ISSUE THREAD

**Issue by zachholcomb** [tylerpporter/find_my_market_api#24]
- [x] Create Token model
- [x] Create Token Payload model
- [x] Update User model to return favorites in final response
