### ISSUE TITLE
User Can Favorite a Market

### ISSUE THREAD

**Issue by tylerpporter** [tylerpporter/find_my_market_api#27]
- [x]  Create joins table `favorites`
 - [x] Create `markets` table 
- [x] Set up relationships 
- [x] Create CRUD endpoints
